# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'iOS7ColorsSample' do
  use_frameworks!

  # When I'm testing new versions of the library, use a local podspec
  # pod 'iOS7Colors', :path => '~/code/HJS/HJSKit/HJSUtils_Support/iOS7Colors'
  # Here's the "normal" podspec to use the custom fork.
  pod 'iOS7Colors', :git => 'https://github.com/HiddenJester/iOS7Colors.git'
end
